In [20]:
import tensorflow as tf
import numpy as np

In [21]:
x=tf.placeholder(tf.float32,[None,1])

In [22]:
data = np.random.randn(1000,1)

In [23]:
sess=tf.Session()

In [24]:
sess.run(tf.global_variables_initializer())

In [25]:
a=sess.run(x,feed_dict={x:data.tolist()})

In [26]:
a

array([[ 1.19940412],
       [ 1.29633749],
       [-0.00525713],
       [-1.87017012],
       [ 1.97114754],
       [ 2.18459487],
       [ 0.26673472],
       [ 0.21393745],
       [-0.57046109],
       [ 1.03572631],
       [-0.56057191],
       [-0.46781483],
       [-0.49908298],
       [ 0.86290908],
       [ 2.02249599],
       [ 0.61847645],
       [ 0.10899606],
       [-1.87459028],
       [ 0.53886247],
       [-2.06014776],
       [-1.34137249],
       [ 1.02452564],
       [-0.63299918],
       [-0.27298373],
       [-0.74460524],
       [-1.10238492],
       [-0.3242991 ],
       [ 1.17126095],
       [-1.1523596 ],
       [-0.70428753],
       [-0.1171756 ],
       [ 0.49242428],
       [-0.30829886],
       [-0.59118474],
       [ 1.0227561 ],
       [-1.35575068],
       [-1.86059785],
       [-0.32814172],
       [-2.13172126],
       [-1.91517615],
       [ 0.39928293],
       [-0.64037663],
       [-1.21926022],
       [-1.03537452],
       [-0.25652289],
       [ 0

In [27]:
a=sess.run(x,feed_dict={x:data})

In [28]:
a

array([[ 1.19940412],
       [ 1.29633749],
       [-0.00525713],
       [-1.87017012],
       [ 1.97114754],
       [ 2.18459487],
       [ 0.26673472],
       [ 0.21393745],
       [-0.57046109],
       [ 1.03572631],
       [-0.56057191],
       [-0.46781483],
       [-0.49908298],
       [ 0.86290908],
       [ 2.02249599],
       [ 0.61847645],
       [ 0.10899606],
       [-1.87459028],
       [ 0.53886247],
       [-2.06014776],
       [-1.34137249],
       [ 1.02452564],
       [-0.63299918],
       [-0.27298373],
       [-0.74460524],
       [-1.10238492],
       [-0.3242991 ],
       [ 1.17126095],
       [-1.1523596 ],
       [-0.70428753],
       [-0.1171756 ],
       [ 0.49242428],
       [-0.30829886],
       [-0.59118474],
       [ 1.0227561 ],
       [-1.35575068],
       [-1.86059785],
       [-0.32814172],
       [-2.13172126],
       [-1.91517615],
       [ 0.39928293],
       [-0.64037663],
       [-1.21926022],
       [-1.03537452],
       [-0.25652289],
       [ 0

In [29]:
data.shape

(1000, 1)

In [30]:
type(data)

numpy.ndarray

In [31]:
datab=np.ones([1000,1])

In [32]:
b=sess.run(x,feed_dict={x:datab})

In [33]:
data.shape

(1000, 1)

In [36]:
np.ndarray((100,1))

array([[  5.76580140e+074],
       [  9.08367203e+223],
       [  5.76580184e+074],
       [  9.08367203e+223],
       [  6.97291386e+252],
       [  2.19993033e-152],
       [  1.94855600e+227],
       [  2.98058770e+228],
       [  9.08367203e+223],
       [  4.93418090e+257],
       [  2.47436711e+155],
       [  4.20482868e+093],
       [  6.16809414e+223],
       [  2.66360021e+233],
       [  4.24514132e+175],
       [  4.91459297e+252],
       [  2.51715952e+180],
       [  4.91459297e+252],
       [  7.50187034e+247],
       [  1.09892467e+155],
       [  1.71877285e+161],
       [  1.66828006e+243],
       [  9.66427243e-153],
       [  1.09891550e+155],
       [  2.44036531e-152],
       [  4.81431724e+199],
       [  1.06400250e+248],
       [  2.35054197e+180],
       [  7.69972395e+218],
       [  5.02493243e+180],
       [  1.11487288e+219],
       [  1.10154444e+155],
       [  2.87247029e+161],
       [  4.26137297e+257],
       [  1.02189320e-152],
       [  5.31361512